# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-99292f4d-fda6-4bce-9ff5-f6b344d1e449";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-99292f4d-fda6-4bce-9ff5-f6b344d1e449".device = "/dev/disk/by-uuid/99292f4d-fda6-4bce-9ff5-f6b344d1e449";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/86A7-6521";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d5a84443-b5a5-485b-848e-8c50df120425"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
